steps:
  # Build the Docker image (includes npm build)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tsukiuta-web:$SHORT_SHA'
      - '--build-arg'
      - 'REACT_APP_CLAUDE_API_KEY=${_CLAUDE_API_KEY}'
      - '--build-arg'
      - 'REACT_APP_SUPABASE_URL=${_SUPABASE_URL}'
      - '--build-arg'
      - 'REACT_APP_SUPABASE_ANON_KEY=${_SUPABASE_ANON_KEY}'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tsukiuta-web:$SHORT_SHA'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tsukiuta-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tsukiuta-web:$SHORT_SHA'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/tsukiuta-web:$SHORT_SHA'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
