steps:
  # Secret Managerから環境変数を取得
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$CLAUDE_API_KEY" > /workspace/claude_key.txt
        echo "$$SUPABASE_URL" > /workspace/supabase_url.txt
        echo "$$SUPABASE_ANON_KEY" > /workspace/supabase_key.txt
    secretEnv: ['CLAUDE_API_KEY', 'SUPABASE_URL', 'SUPABASE_ANON_KEY']

  # Build the Docker image with secrets
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --no-cache \
          -t gcr.io/$PROJECT_ID/tsukiuta-web:$BUILD_ID \
          --build-arg REACT_APP_CLAUDE_API_KEY="$(cat /workspace/claude_key.txt)" \
          --build-arg REACT_APP_SUPABASE_URL="$(cat /workspace/supabase_url.txt)" \
          --build-arg REACT_APP_SUPABASE_ANON_KEY="$(cat /workspace/supabase_key.txt)" \
          .

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/tsukiuta-web:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'tsukiuta-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tsukiuta-web:$BUILD_ID'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--min-instances'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/tsukiuta-web:$BUILD_ID'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'

# Secret Managerの設定
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/claude-api-key/versions/latest
      env: 'CLAUDE_API_KEY'
    - versionName: projects/${PROJECT_ID}/secrets/supabase-url/versions/latest
      env: 'SUPABASE_URL'
    - versionName: projects/${PROJECT_ID}/secrets/supabase-anon-key/versions/latest
      env: 'SUPABASE_ANON_KEY'